[rospy.client][INFO] 2024-10-18 23:11:07,851: init_node, name[/rqt_gui_py_node_11785], pid[11785]
[xmlrpc][INFO] 2024-10-18 23:11:07,853: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2024-10-18 23:11:07,854: Started XML-RPC server [http://nx:43973/]
[rospy.init][INFO] 2024-10-18 23:11:07,854: ROS Slave URI: [http://nx:43973/]
[rospy.impl.masterslave][INFO] 2024-10-18 23:11:07,855: _ready: http://nx:43973/
[rospy.registration][INFO] 2024-10-18 23:11:07,857: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2024-10-18 23:11:07,857: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2024-10-18 23:11:07,956: registered with master
[rospy.rosout][INFO] 2024-10-18 23:11:07,957: initializing /rosout core topic
[rospy.rosout][INFO] 2024-10-18 23:11:07,961: connected to core topic /rosout
[rospy.simtime][INFO] 2024-10-18 23:11:07,963: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2024-10-18 23:11:08,205: topic[/rosout] adding connection to [/rosout], count 0
[rosgraph.graph][ERROR] 2024-10-18 23:11:08,564: cannot get stats info from node [/map_saver]: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/impl/graph.py", line 395, in _node_refresh_businfo
    code, msg, bus_info = api.getBusInfo(_ROS_NAME)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 894, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 856, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 833, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 22] Invalid argument

